export {Baner} from './homeSection/baner/Baner'
export {Brand} from './homeSection/brand/Brand'
export {Project} from './homeSection/project/Project'
export {Advertising} from './homeSection/advertising/Advertising'
export {Footer} from './homeSection/footer/Footer'